name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.3', '7.4']
        composer-flags: ['']
        include:
          - { php-version: '8.0', composer-flags: '--ignore-platform-req=php' }

    name: CI PHP ${{ matrix.php-version }} ${{ matrix.composer-flags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: composer:v2

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install composer-flags
        run: |
          composer update --prefer-dist --no-interaction --no-progress ${{ matrix.composer-flags }}

      - name: Execute tests
        run: |
          make ci-test

      - name: Upload coverage report
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          php vendor/bin/php-coveralls -v

      - name: Validate composer.json
        run: |
          composer validate --strict
          composer normalize --diff --dry-run
